    # annsonnie playbook.yml
---
- name: Ansible playbook to dockerize and run yolo e-commerce app
  hosts: all
  become: true
  roles:
    - frontend-deployment
    - setup-mongodb
    - backend-deployment
    