---
- name: Pull MongoDB Docker image
  docker_container:
    name: app-mongo
    image: mongo:latest
    state: started
    ports:
      - "27017:27017"
    volumes:
      - name: app-mongo-data
        path: /data/db